/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Agents */
        get: operations["list_agents_v1_agents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agents/bindings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Bindings */
        get: operations["list_bindings_v1_agents_bindings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agents/bindings/{agent_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Upsert Binding */
        put: operations["upsert_binding_v1_agents_bindings__agent_id__put"];
        post?: never;
        /** Delete Binding */
        delete: operations["delete_binding_v1_agents_bindings__agent_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Forgot Password
         * @description Always returns 200 — never reveal whether the email exists.
         */
        post: operations["forgot_password_v1_auth_forgot_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset Password */
        post: operations["reset_password_v1_auth_reset_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/verify-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify Email */
        post: operations["verify_email_v1_auth_verify_email_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/bundles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Bundles */
        get: operations["list_bundles_v1_bundles_get"];
        put?: never;
        /** Create Bundle */
        post: operations["create_bundle_v1_bundles_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/bundles/{bundle_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Bundle */
        get: operations["get_bundle_v1_bundles__bundle_id__get"];
        /** Update Bundle */
        put: operations["update_bundle_v1_bundles__bundle_id__put"];
        post?: never;
        /** Delete Bundle */
        delete: operations["delete_bundle_v1_bundles__bundle_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/devices/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve
         * @description Session-authed: bind a pending device-code grant to the current user
         *     and chosen workspace. Verifies the user is a member of that workspace
         *     (otherwise it would be a confused-deputy: an attacker who tricked you
         *     into running `thomas cloud login` could attach the device to their
         *     workspace).
         */
        post: operations["approve_v1_devices_approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/devices/begin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Begin */
        post: operations["begin_v1_devices_begin_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/devices/poll": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Poll */
        post: operations["poll_v1_devices_poll_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_v1_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/policies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Policies */
        get: operations["list_policies_v1_policies_get"];
        put?: never;
        /** Create Policy */
        post: operations["create_policy_v1_policies_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/policies/{policy_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Policy */
        get: operations["get_policy_v1_policies__policy_id__get"];
        /** Update Policy */
        put: operations["update_policy_v1_policies__policy_id__put"];
        post?: never;
        /** Delete Policy */
        delete: operations["delete_policy_v1_policies__policy_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Providers */
        get: operations["list_providers_v1_providers_get"];
        put?: never;
        /** Upsert Provider */
        post: operations["upsert_provider_v1_providers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/providers/{provider_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Provider */
        delete: operations["delete_provider_v1_providers__provider_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs_v1_runs_get"];
        put?: never;
        /** Upload Runs */
        post: operations["upload_runs_v1_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sync */
        get: operations["sync_v1_sync_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AgentBindingListResponse */
        AgentBindingListResponse: {
            /** Bindings */
            bindings: components["schemas"]["AgentBindingResponse"][];
        };
        /** AgentBindingResponse */
        AgentBindingResponse: {
            /** Agentid */
            agentId: string;
            /** Bindingkind */
            bindingKind: string;
            staticTarget?: components["schemas"]["ModelRef"] | null;
            /** Targetid */
            targetId?: string | null;
            /** Updatedat */
            updatedAt: string;
        };
        /** AgentBindingUpsertRequest */
        AgentBindingUpsertRequest: {
            /**
             * Bindingkind
             * @enum {string}
             */
            bindingKind: "policy" | "bundle" | "static";
            staticTarget?: components["schemas"]["ModelRef"] | null;
            /** Targetid */
            targetId?: string | null;
        };
        /** AgentsResponse */
        AgentsResponse: {
            /** Agents */
            agents: components["schemas"]["AgentStats"][];
        };
        /** AgentStats */
        AgentStats: {
            /** Agentid */
            agentId: string;
            /** Calls24H */
            calls24h: number;
            /** Errors24H */
            errors24h: number;
            /** Lasterror */
            lastError: string | null;
            /** Lastrequestat */
            lastRequestAt: string | null;
            /** Lasttargetmodel */
            lastTargetModel: string | null;
            /** Lasttargetprovider */
            lastTargetProvider: string | null;
            /** Spend24H */
            spend24h: number | null;
        };
        /**
         * ApproveRequest
         * @description Web → API: approve a pending device-code grant for the current user.
         */
        ApproveRequest: {
            /** User Code */
            user_code: string;
            /** Workspace Id */
            workspace_id: string;
        };
        /** ApproveResponse */
        ApproveResponse: {
            /** Device Code */
            device_code: string;
            /** Status */
            status: string;
        };
        /** BeginRequest */
        BeginRequest: {
            /**
             * Label
             * @default unnamed device
             */
            label: string;
            /** Platform */
            platform?: string | null;
            /** Thomas Version */
            thomas_version?: string | null;
        };
        /** BeginResponse */
        BeginResponse: {
            /** Device Code */
            device_code: string;
            /** Expires In */
            expires_in: number;
            /** Interval */
            interval: number;
            /** User Code */
            user_code: string;
            /** Verification Uri */
            verification_uri: string;
            /** Verification Uri Complete */
            verification_uri_complete: string;
        };
        /** BundleCreateRequest */
        BundleCreateRequest: {
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /** Name */
            name: string;
            spec: components["schemas"]["BundleSpec"];
        };
        /** BundleLeg */
        BundleLeg: {
            /** Capcallsperday */
            capCallsPerDay?: number | null;
            /** Capusdperday */
            capUsdPerDay?: number | null;
            /** Model */
            model: string;
            /**
             * Priority
             * @default 0
             */
            priority: number;
            /** Providerid */
            providerId: string;
        };
        /** BundleListResponse */
        BundleListResponse: {
            /** Bundles */
            bundles: components["schemas"]["BundleResponse"][];
        };
        /** BundleResponse */
        BundleResponse: {
            /** Createdat */
            createdAt: string;
            /** Enabled */
            enabled: boolean;
            /** Id */
            id: string;
            /** Name */
            name: string;
            spec: components["schemas"]["BundleSpec"];
            /** Updatedat */
            updatedAt: string;
        };
        /** BundleSpec */
        BundleSpec: {
            /** Legs */
            legs: components["schemas"]["BundleLeg"][];
            /**
             * Schemaversion
             * @default 1
             * @constant
             */
            schemaVersion: 1;
        };
        /** BundleUpdateRequest */
        BundleUpdateRequest: {
            /** Enabled */
            enabled?: boolean | null;
            /** Name */
            name?: string | null;
            spec?: components["schemas"]["BundleSpec"] | null;
        };
        /** CascadeStep */
        CascadeStep: {
            fallback: components["schemas"]["ModelRef"];
            /** Triggercallsday */
            triggerCallsDay?: number | null;
            /** Triggerspenddayusd */
            triggerSpendDayUsd?: number | null;
        };
        /** ForgotPasswordRequest */
        ForgotPasswordRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** MeResponse */
        MeResponse: {
            /** Email */
            email: string;
            /** Emailverified */
            emailVerified: boolean;
            /** Userid */
            userId: number;
            /** Workspaces */
            workspaces: components["schemas"]["WorkspaceSummary"][];
        };
        /**
         * ModelRef
         * @description A (provider, model) pair. Used inside policy / bundle specs.
         */
        ModelRef: {
            /** Model */
            model: string;
            /** Providerid */
            providerId: string;
        };
        /** PolicyCreateRequest */
        PolicyCreateRequest: {
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /** Name */
            name: string;
            spec: components["schemas"]["PolicySpec"];
        };
        /** PolicyListResponse */
        PolicyListResponse: {
            /** Policies */
            policies: components["schemas"]["PolicyResponse"][];
        };
        /** PolicyResponse */
        PolicyResponse: {
            /** Createdat */
            createdAt: string;
            /** Enabled */
            enabled: boolean;
            /** Id */
            id: string;
            /** Name */
            name: string;
            spec: components["schemas"]["PolicySpec"];
            /** Updatedat */
            updatedAt: string;
        };
        /** PolicySpec */
        PolicySpec: {
            /** Cascade */
            cascade?: components["schemas"]["CascadeStep"][];
            failoverTo?: components["schemas"]["ModelRef"] | null;
            primary: components["schemas"]["ModelRef"];
            /**
             * Schemaversion
             * @default 1
             * @constant
             */
            schemaVersion: 1;
        };
        /**
         * PolicyUpdateRequest
         * @description All fields optional — PATCH-like semantics on PUT.
         */
        PolicyUpdateRequest: {
            /** Enabled */
            enabled?: boolean | null;
            /** Name */
            name?: string | null;
            spec?: components["schemas"]["PolicySpec"] | null;
        };
        /** PollRequest */
        PollRequest: {
            /** Device Code */
            device_code: string;
        };
        /** PollResponse */
        PollResponse: {
            /** Device Id */
            device_id: string;
            /** Device Token */
            device_token: string;
            /** Workspace Id */
            workspace_id: string;
        };
        /** ProviderListResponse */
        ProviderListResponse: {
            /** Providers */
            providers: components["schemas"]["ProviderResponse"][];
        };
        /** ProviderResponse */
        ProviderResponse: {
            /** Isbuiltin */
            isBuiltin: boolean;
            /** Originbaseurl */
            originBaseUrl?: string | null;
            /** Protocol */
            protocol: string;
            /** Providerid */
            providerId: string;
            /** Reportedbydeviceid */
            reportedByDeviceId?: string | null;
            /** Updatedat */
            updatedAt: string;
        };
        /** ProviderUpsertRequest */
        ProviderUpsertRequest: {
            /**
             * Isbuiltin
             * @default false
             */
            isBuiltin: boolean;
            /** Originbaseurl */
            originBaseUrl?: string | null;
            /**
             * Protocol
             * @enum {string}
             */
            protocol: "openai" | "anthropic";
            /** Providerid */
            providerId: string;
        };
        /** RegisterRequest */
        RegisterRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** ResetPasswordRequest */
        ResetPasswordRequest: {
            /** Password */
            password: string;
            /** Token */
            token: string;
        };
        /** RunBatchRequest */
        RunBatchRequest: {
            /** Runs */
            runs: components["schemas"]["RunIn"][];
        };
        /** RunBatchResponse */
        RunBatchResponse: {
            /** Accepted */
            accepted: number;
            /** Duplicates */
            duplicates: number;
        };
        /** RunIn */
        RunIn: {
            /** Agentid */
            agentId: string;
            /** Cost */
            cost?: number | null;
            /** Durationms */
            durationMs: number;
            /** Endedat */
            endedAt: string;
            /** Errormessage */
            errorMessage?: string | null;
            /** Failovernote */
            failoverNote?: string | null;
            /**
             * Failovers
             * @default 0
             */
            failovers: number;
            /** Httpstatus */
            httpStatus: number;
            /**
             * Inboundprotocol
             * @enum {string}
             */
            inboundProtocol: "anthropic" | "openai";
            /** Inputtokens */
            inputTokens: number;
            /** Outboundmodel */
            outboundModel: string;
            /** Outboundprovider */
            outboundProvider: string;
            /** Outputtokens */
            outputTokens: number;
            /** Policyid */
            policyId?: string | null;
            /** Policysource */
            policySource?: ("cloud" | "local" | "none") | null;
            /** Runid */
            runId: string;
            /** Startedat */
            startedAt: string;
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "error";
            /** Streamed */
            streamed: boolean;
        };
        /** RunListResponse */
        RunListResponse: {
            /** Runs */
            runs: components["schemas"]["RunResponse"][];
        };
        /** RunResponse */
        RunResponse: {
            /** Agentid */
            agentId: string;
            /** Cost */
            cost: number | null;
            /** Durationms */
            durationMs: number;
            /** Endedat */
            endedAt: string;
            /** Errormessage */
            errorMessage: string | null;
            /** Failovernote */
            failoverNote: string | null;
            /** Failovers */
            failovers: number;
            /** Httpstatus */
            httpStatus: number;
            /** Id */
            id: string;
            /** Inboundprotocol */
            inboundProtocol: string;
            /** Inputtokens */
            inputTokens: number;
            /** Outboundmodel */
            outboundModel: string;
            /** Outboundprovider */
            outboundProvider: string;
            /** Outputtokens */
            outputTokens: number;
            /** Policyid */
            policyId: string | null;
            /** Policysource */
            policySource: string | null;
            /** Runid */
            runId: string;
            /** Startedat */
            startedAt: string;
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "error";
            /** Streamed */
            streamed: boolean;
        };
        /** StatusResponse */
        StatusResponse: {
            /** Status */
            status: string;
        };
        /** SyncResponse */
        SyncResponse: {
            /** Bindings */
            bindings: components["schemas"]["AgentBindingResponse"][];
            /** Bundles */
            bundles: components["schemas"]["BundleResponse"][];
            /** Policies */
            policies: components["schemas"]["PolicyResponse"][];
            /** Providers */
            providers: components["schemas"]["ProviderResponse"][];
            /** Redactrulesversion */
            redactRulesVersion?: string | null;
            /**
             * Schemaversion
             * @default 1
             */
            schemaVersion: number;
        };
        /** UserResponse */
        UserResponse: {
            /** Email */
            email: string;
            /** Emailverified */
            emailVerified: boolean;
            /** Userid */
            userId: number;
            /** Workspaces */
            workspaces: components["schemas"]["WorkspaceSummary"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** VerifyEmailRequest */
        VerifyEmailRequest: {
            /** Token */
            token: string;
        };
        /** WorkspaceSummary */
        WorkspaceSummary: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Role */
            role: string;
            /** Tier */
            tier: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type SchemaAgentBindingListResponse = components['schemas']['AgentBindingListResponse'];
export type SchemaAgentBindingResponse = components['schemas']['AgentBindingResponse'];
export type SchemaAgentBindingUpsertRequest = components['schemas']['AgentBindingUpsertRequest'];
export type SchemaAgentsResponse = components['schemas']['AgentsResponse'];
export type SchemaAgentStats = components['schemas']['AgentStats'];
export type SchemaApproveRequest = components['schemas']['ApproveRequest'];
export type SchemaApproveResponse = components['schemas']['ApproveResponse'];
export type SchemaBeginRequest = components['schemas']['BeginRequest'];
export type SchemaBeginResponse = components['schemas']['BeginResponse'];
export type SchemaBundleCreateRequest = components['schemas']['BundleCreateRequest'];
export type SchemaBundleLeg = components['schemas']['BundleLeg'];
export type SchemaBundleListResponse = components['schemas']['BundleListResponse'];
export type SchemaBundleResponse = components['schemas']['BundleResponse'];
export type SchemaBundleSpec = components['schemas']['BundleSpec'];
export type SchemaBundleUpdateRequest = components['schemas']['BundleUpdateRequest'];
export type SchemaCascadeStep = components['schemas']['CascadeStep'];
export type SchemaForgotPasswordRequest = components['schemas']['ForgotPasswordRequest'];
export type SchemaHttpValidationError = components['schemas']['HTTPValidationError'];
export type SchemaLoginRequest = components['schemas']['LoginRequest'];
export type SchemaMeResponse = components['schemas']['MeResponse'];
export type SchemaModelRef = components['schemas']['ModelRef'];
export type SchemaPolicyCreateRequest = components['schemas']['PolicyCreateRequest'];
export type SchemaPolicyListResponse = components['schemas']['PolicyListResponse'];
export type SchemaPolicyResponse = components['schemas']['PolicyResponse'];
export type SchemaPolicySpec = components['schemas']['PolicySpec'];
export type SchemaPolicyUpdateRequest = components['schemas']['PolicyUpdateRequest'];
export type SchemaPollRequest = components['schemas']['PollRequest'];
export type SchemaPollResponse = components['schemas']['PollResponse'];
export type SchemaProviderListResponse = components['schemas']['ProviderListResponse'];
export type SchemaProviderResponse = components['schemas']['ProviderResponse'];
export type SchemaProviderUpsertRequest = components['schemas']['ProviderUpsertRequest'];
export type SchemaRegisterRequest = components['schemas']['RegisterRequest'];
export type SchemaResetPasswordRequest = components['schemas']['ResetPasswordRequest'];
export type SchemaRunBatchRequest = components['schemas']['RunBatchRequest'];
export type SchemaRunBatchResponse = components['schemas']['RunBatchResponse'];
export type SchemaRunIn = components['schemas']['RunIn'];
export type SchemaRunListResponse = components['schemas']['RunListResponse'];
export type SchemaRunResponse = components['schemas']['RunResponse'];
export type SchemaStatusResponse = components['schemas']['StatusResponse'];
export type SchemaSyncResponse = components['schemas']['SyncResponse'];
export type SchemaUserResponse = components['schemas']['UserResponse'];
export type SchemaValidationError = components['schemas']['ValidationError'];
export type SchemaVerifyEmailRequest = components['schemas']['VerifyEmailRequest'];
export type SchemaWorkspaceSummary = components['schemas']['WorkspaceSummary'];
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: boolean | string;
                    };
                };
            };
        };
    };
    list_agents_v1_agents_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: {
                tc_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_bindings_v1_agents_bindings_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: {
                tc_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentBindingListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upsert_binding_v1_agents_bindings__agent_id__put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                agent_id: string;
            };
            cookie?: {
                tc_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentBindingUpsertRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentBindingResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_binding_v1_agents_bindings__agent_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                agent_id: string;
            };
            cookie?: {
                tc_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    forgot_password_v1_auth_forgot_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForgotPasswordRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: {
                "user-agent"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: {
                tc_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_password_v1_auth_reset_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPasswordRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_email_v1_auth_verify_email_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyEmailRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_bundles_v1_bundles_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: {
                tc_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BundleListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_bundle_v1_bundles_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: {
                tc_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BundleCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BundleResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_bundle_v1_bundles__bundle_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                bundle_id: string;
            };
            cookie?: {
                tc_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BundleResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_bundle_v1_bundles__bundle_id__put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                bundle_id: string;
            };
            cookie?: {
                tc_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BundleUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BundleResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_bundle_v1_bundles__bundle_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                bundle_id: string;
            };
            cookie?: {
                tc_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_v1_devices_approve_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: {
                tc_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApproveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApproveResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    begin_v1_devices_begin_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BeginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BeginResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    poll_v1_devices_poll_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PollRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PollResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_v1_me_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: {
                tc_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_policies_v1_policies_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: {
                tc_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_policy_v1_policies_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: {
                tc_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PolicyCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_policy_v1_policies__policy_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                policy_id: string;
            };
            cookie?: {
                tc_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_policy_v1_policies__policy_id__put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                policy_id: string;
            };
            cookie?: {
                tc_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PolicyUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_policy_v1_policies__policy_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                policy_id: string;
            };
            cookie?: {
                tc_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_providers_v1_providers_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: {
                tc_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upsert_provider_v1_providers_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: {
                tc_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProviderUpsertRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_provider_v1_providers__provider_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                provider_id: string;
            };
            cookie?: {
                tc_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_runs_v1_runs_get: {
        parameters: {
            query?: {
                agentId?: string | null;
                limit?: number;
                since?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: {
                tc_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_runs_v1_runs_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunBatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunBatchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_v1_sync_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
